In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

/Users/junpark/.pyenv/versions/3.10.13/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
gemmapro = AutoModelForCausalLM.from_pretrained("./gemma-ko-2b-dev")

Gemma's activation function should be approximate GeLU and not exact GeLU.
Changing the activation function to `gelu_pytorch_tanh`.if you want to use the legacy `gelu`, edit the `model.config` to set `hidden_activation=gelu`   instead of `hidden_act`. See https://github.com/huggingface/transformers/pull/29402 for more details.
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.08s/it]


In [3]:
gemma = AutoModelForCausalLM.from_pretrained("google/gemma-2b")

Loading checkpoint shards: 100%|██████████| 2/2 [00:09<00:00,  4.72s/it]


In [4]:
for name, param in gemma.named_parameters():
    print(name)

model.embed_tokens.weight
model.layers.0.self_attn.q_proj.weight
model.layers.0.self_attn.k_proj.weight
model.layers.0.self_attn.v_proj.weight
model.layers.0.self_attn.o_proj.weight
model.layers.0.mlp.gate_proj.weight
model.layers.0.mlp.up_proj.weight
model.layers.0.mlp.down_proj.weight
model.layers.0.input_layernorm.weight
model.layers.0.post_attention_layernorm.weight
model.layers.1.self_attn.q_proj.weight
model.layers.1.self_attn.k_proj.weight
model.layers.1.self_attn.v_proj.weight
model.layers.1.self_attn.o_proj.weight
model.layers.1.mlp.gate_proj.weight
model.layers.1.mlp.up_proj.weight
model.layers.1.mlp.down_proj.weight
model.layers.1.input_layernorm.weight
model.layers.1.post_attention_layernorm.weight
model.layers.2.self_attn.q_proj.weight
model.layers.2.self_attn.k_proj.weight
model.layers.2.self_attn.v_proj.weight
model.layers.2.self_attn.o_proj.weight
model.layers.2.mlp.gate_proj.weight
model.layers.2.mlp.up_proj.weight
model.layers.2.mlp.down_proj.weight
model.layers.2.inp

In [5]:
for name, param in gemmapro.named_parameters():
    print(name)

model.embed_tokens.weight
model.layers.0.self_attn.q_proj.weight
model.layers.0.self_attn.k_proj.weight
model.layers.0.self_attn.v_proj.weight
model.layers.0.self_attn.o_proj.weight
model.layers.0.mlp.gate_proj.weight
model.layers.0.mlp.up_proj.weight
model.layers.0.mlp.down_proj.weight
model.layers.0.input_layernorm.weight
model.layers.0.post_attention_layernorm.weight
model.layers.1.self_attn.q_proj.weight
model.layers.1.self_attn.k_proj.weight
model.layers.1.self_attn.v_proj.weight
model.layers.1.self_attn.o_proj.weight
model.layers.1.mlp.gate_proj.weight
model.layers.1.mlp.up_proj.weight
model.layers.1.mlp.down_proj.weight
model.layers.1.input_layernorm.weight
model.layers.1.post_attention_layernorm.weight
model.layers.2.self_attn.q_proj.weight
model.layers.2.self_attn.k_proj.weight
model.layers.2.self_attn.v_proj.weight
model.layers.2.self_attn.o_proj.weight
model.layers.2.mlp.gate_proj.weight
model.layers.2.mlp.up_proj.weight
model.layers.2.mlp.down_proj.weight
model.layers.2.inp

In [6]:
gemmapro_dict = dict(gemmapro.named_parameters())
gemma_dict = dict(gemma.named_parameters())

In [7]:
import torch

torch.all(
    gemmapro_dict["model.embed_tokens.weight"]
    == gemma_dict["model.embed_tokens.weight"]
)

tensor(True)

In [8]:
torch.all(gemmapro_dict["model.norm.weight"] == gemma_dict["model.norm.weight"])

tensor(True)

In [9]:
# 기존 layer 검사
for i in range(18):
    b = i // 6
    pi = i + b  # pro index
    print(pi, i)
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.q_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.q_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.k_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.k_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.v_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.v_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.o_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.o_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.gate_proj.weight"]
            == gemma_dict[f"model.layers.{i}.mlp.gate_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.up_proj.weight"]
            == gemma_dict[f"model.layers.{i}.mlp.up_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.down_proj.weight"]
            == gemma_dict[f"model.layers.{i}.mlp.down_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.input_layernorm.weight"]
            == gemma_dict[f"model.layers.{i}.input_layernorm.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.post_attention_layernorm.weight"]
            == gemma_dict[f"model.layers.{i}.post_attention_layernorm.weight"]
        )
    )

0 0
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
1 1
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
2 2
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
3 3
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
4 4
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
5 5
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
7 6
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
8 7
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
9 8
tensor(True)
tensor(True)
te

In [10]:
# expanded layer 검사
for pi, i in [
    (6, 5),
    (13, 11),
    (20, 17),
]:
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.q_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.q_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.k_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.k_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.v_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.v_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.o_proj.weight"]
            == gemma_dict[f"model.layers.{i}.self_attn.o_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.gate_proj.weight"]
            == gemma_dict[f"model.layers.{i}.mlp.gate_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.up_proj.weight"]
            == gemma_dict[f"model.layers.{i}.mlp.up_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.down_proj.weight"]
            == gemma_dict[f"model.layers.{i}.mlp.down_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.input_layernorm.weight"]
            == gemma_dict[f"model.layers.{i}.input_layernorm.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.post_attention_layernorm.weight"]
            == gemma_dict[f"model.layers.{i}.post_attention_layernorm.weight"]
        )
    )

tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)


In [11]:
# expanded layer 검사
for pi in (6, 13, 20):
    print(pi)
    print(gemmapro_dict[f"model.layers.{pi}.self_attn.q_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.self_attn.k_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.self_attn.v_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.self_attn.o_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.mlp.gate_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.mlp.up_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.mlp.down_proj.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.input_layernorm.weight"])
    print(gemmapro_dict[f"model.layers.{pi}.post_attention_layernorm.weight"])
    print("----------------------")

6
Parameter containing:
tensor([[-0.0591,  0.0115, -0.0120,  ...,  0.0214, -0.0066,  0.0330],
        [-0.0654,  0.0199, -0.0284,  ...,  0.0271, -0.0079,  0.0294],
        [-0.0027, -0.0010, -0.0381,  ..., -0.0520,  0.0366,  0.0003],
        ...,
        [-0.0118,  0.0053, -0.0023,  ...,  0.0013,  0.0059,  0.0006],
        [-0.0011, -0.0054,  0.0026,  ...,  0.0011,  0.0008,  0.0098],
        [-0.0099, -0.0266,  0.0164,  ..., -0.0069, -0.0062,  0.0066]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.0008,  0.0325,  0.0150,  ..., -0.0064, -0.0085, -0.0059],
        [ 0.0186, -0.0101, -0.0148,  ..., -0.0115, -0.0172,  0.0127],
        [ 0.0188, -0.0086, -0.0192,  ...,  0.0002,  0.0089, -0.0066],
        ...,
        [ 0.0302,  0.0208, -0.0688,  ...,  0.0201,  0.0140, -0.0723],
        [-0.0444, -0.0312, -0.0325,  ...,  0.0586,  0.0371,  0.0554],
        [ 0.0161,  0.0159,  0.0432,  ..., -0.0234, -0.0048,  0.0515]],
       requires_grad=True)
Parameter containing:
tensor([[-

In [12]:
for name, param in gemmapro.named_parameters():
    print(name)
    print(param)

model.embed_tokens.weight
Parameter containing:
tensor([[ 5.3516e-01, -3.4668e-02,  9.5215e-02,  ...,  3.9307e-02,
          2.6562e-01,  7.2266e-02],
        [ 1.5137e-01, -1.7188e-01, -1.4160e-01,  ..., -2.4414e-02,
          1.2493e-04, -3.3691e-02],
        [ 1.1914e-01,  1.9165e-02, -3.1738e-02,  ..., -6.5613e-03,
          3.4714e-04, -8.9111e-03],
        ...,
        [ 2.8711e-01, -1.1475e-02,  6.4453e-02,  ..., -5.7861e-02,
          3.3447e-02, -4.0039e-02],
        [ 3.4375e-01, -6.6895e-02,  8.5449e-02,  ..., -8.7891e-03,
          8.0078e-02,  8.1787e-03],
        [ 5.3906e-01, -3.4424e-02,  9.2285e-02,  ...,  3.7842e-02,
          2.6562e-01,  7.1777e-02]], requires_grad=True)
model.layers.0.self_attn.q_proj.weight
Parameter containing:
tensor([[ 4.0436e-04, -1.0742e-02, -1.2207e-02,  ...,  4.8828e-03,
          2.3438e-02, -2.0264e-02],
        [ 1.7834e-04, -2.7588e-02,  7.1106e-03,  ...,  8.2397e-03,
         -1.2512e-03,  1.2756e-02],
        [ 5.7697e-05, -2.4033e-04

In [13]:
gemmaprobase = AutoModelForCausalLM.from_pretrained("gemmathon/gemma-2b-pro")

Loading checkpoint shards: 100%|██████████| 2/2 [00:15<00:00,  7.51s/it]


In [14]:
gemmaprobase_dict = dict(gemmaprobase.named_parameters())

In [15]:
# expanded layer 검사
for pi in (6, 13, 20):
    print(pi)
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.q_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.q_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.k_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.k_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.v_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.v_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.o_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.o_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.gate_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.mlp.gate_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.up_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.mlp.up_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.down_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.mlp.down_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.input_layernorm.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.input_layernorm.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.post_attention_layernorm.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.post_attention_layernorm.weight"]
        )
    )
    print("----------------------")

6
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
----------------------
13
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
----------------------
20
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
----------------------


In [16]:
gemmapro_dict[f"model.layers.{6}.self_attn.o_proj.weight"]

Parameter containing:
tensor([[-4.0531e-05, -5.5134e-07, -2.5511e-05,  ..., -2.3174e-04,
          5.9843e-05,  1.4496e-04],
        [-5.6744e-05,  9.9659e-05, -7.9632e-05,  ..., -5.9605e-05,
         -1.8597e-04,  2.9922e-05],
        [-3.3140e-05,  6.9439e-06, -1.8787e-04,  ...,  2.9087e-05,
         -3.6240e-05,  1.3924e-04],
        ...,
        [ 5.2214e-05,  7.0572e-05, -5.9128e-05,  ..., -4.6968e-05,
         -7.4804e-06, -1.5259e-04],
        [ 1.5068e-04, -6.2943e-05,  1.1265e-05,  ...,  9.4414e-05,
          1.0872e-04, -3.3140e-05],
        [-2.1577e-05,  4.3392e-05,  1.1921e-04,  ..., -9.6798e-05,
          4.0293e-05, -1.3065e-04]], requires_grad=True)

In [17]:
gemmapro_dict[f"model.layers.{13}.mlp.down_proj.weight"]

Parameter containing:
tensor([[ 1.6403e-04,  1.6928e-05, -8.2493e-05,  ..., -1.3733e-04,
         -8.2329e-07, -9.0599e-05],
        [-1.2684e-04, -6.1989e-05,  7.2479e-05,  ..., -3.5316e-06,
         -1.1873e-04,  1.6022e-04],
        [ 4.3869e-05,  7.8678e-05,  1.9360e-04,  ..., -1.5736e-05,
         -2.1362e-04,  3.0398e-05],
        ...,
        [-3.4571e-06, -8.5831e-05,  3.9577e-05,  ...,  9.0122e-05,
         -2.7061e-05,  1.6403e-04],
        [ 3.2187e-05,  1.5163e-04,  1.9550e-05,  ..., -7.5817e-05,
         -1.4663e-05, -9.6798e-05],
        [ 6.5565e-06, -9.4891e-05, -7.0572e-05,  ...,  1.5926e-04,
          4.2677e-05, -1.5736e-04]], requires_grad=True)

In [18]:
torch.all(gemmapro_dict[f"model.layers.{20}.self_attn.o_proj.weight"] == 0)

tensor(False)

In [19]:
# all layer 검사
for pi in range(21):
    print(pi)
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.q_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.q_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.k_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.k_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.v_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.v_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.self_attn.o_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.self_attn.o_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.gate_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.mlp.gate_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.up_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.mlp.up_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.mlp.down_proj.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.mlp.down_proj.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.input_layernorm.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.input_layernorm.weight"]
        )
    )
    print(
        torch.all(
            gemmapro_dict[f"model.layers.{pi}.post_attention_layernorm.weight"]
            == gemmaprobase_dict[f"model.layers.{pi}.post_attention_layernorm.weight"]
        )
    )
    print("----------------------")

0
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
----------------------
1
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
----------------------
2
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
----------------------
3
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
----------------------
4
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
----------------------
5
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
----------------------
6
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
tensor(False)
--------------------